---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push
    - tag

steps:
<<<<<<< HEAD
  - name: Generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: Audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate --production

  - name: Install
    image: node:12
    commands:
      - npm ci
    environment:
      # Cannot be true because of node-sass
      NPM_CONFIG_IGNORE_SCRIPTS: false

  - name: test
    image: node:12
    commands:
      - npm test

  #- name: check-coverage
  #  image: node:12
  #  commands:
  #    - npm run check-coverage

  - name: Build
    image: node:12
    commands:
      - npm run build

  - name: Static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: npm
    image: plugins/npm
    settings:
      registry: 'https://registry.npmjs.org/'
      token:
        from_secret: npm_token
    when:
      event: tag
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:
  - name: Publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: npm_token
data: /6rEvowsIHNgc5uWYdOuoD6dyNkbUrWXcVs1SoUejpQr75PEF9UHK9SFAa9tXpFjidKSCx4dPqNmrZ0Tt6svlw==
---
kind: secret
name: ssh_key
data: 61tdu9CXOLn9MPG2q+ss1mV9fM5U+RcliVndBGE6TCqzCDSk3a2IzbLvTXB3IN7g1RJ88OWv+3leATxJWMRcCtj5+MzbdItQf9A4Q+7OqS4nYs5uJD+cNrSqnTviAHRySY9pVV+Aci2Kv/OjAQb3bwaDyV/SNu6k5ZOq/7k58kuHOR5irAT1g0HRK1c2JleWm6vK9s2RlQQjHkq7FMXiW6vp9VDTSAlyDURDUTbVblviCuOXLphkwXbWtnne10uMZKTQWWLdwiVe3Rzm6Y8dEV+caB8VadqJeAnIs5bFMdh20wFKCjQXoq6hSixFNMcqT0k735nJ8TTJ/Aip16sHYEDpc8RPRWO1BFcy/jO1eSEqb5Q23CnHmkDKf4AbzgleWMucT9a5g0FxZw1BiYCc3f3vlOpcKC0Xhji/fswLJJqcrNEi0c+9v8pR+fA+iWBOIH3xy2klHprB9qaDtKZuGSPF3fC3J4VyvRsb3CP1Cf9syCxIYMbCATmQVi0zFML4qbNMr8oseouN8fQOV3exfK6ra300nfEXceMnDe0zDYM2KdjbNMniQdSYXlfFEhNq9szTVDgNEt1EgugE5n4mz4a6Dm2CqShR0G51zVJlnBsZcA2+m3Ag3ZabkEOqfllm9YRqi5UskSkYnXaKmUpAfJJWriKArUz3OAbYe1hqJdy8xZxr9OxhoR8eDQ+HziauRe3+BK1HHU71fncfgU/asnaBrPtrZvIvkEAbnAdzJZLucBjQiorBZBkYbXksAMEBAPFzlMlgQg6KW91etdOIn2Z0X/zhWuGp5tVDJDPW6y5LsHdhUI2rJJkAETJ/n7DwMr9DevISXT15fblqAhhb6Z23bH/5PrrA2r/Ry2EAy/NYMWp5rwNYGrxrkytrctLh3ok9RNNnaF8+VKh/A77lnH6G6od8T/XHn3jpkbHcxiOSOMQT5GpwaG06sLML6hwF8WH3zsRgqVoYgSXDvhTVtdEfhw6EKUALQy5z94vwowX1M8e2TpTmx8ZDVx2bPU7r2mLGoMC+0EkPtADAGnyVwUz52Rwq23pI1hj2Z9V/FhnS1+dvnOhr0hVRxXO3qpPn287hMIhtEr/XMe6TftQKh09CbzgOJ8knqtSWdg3fvh2cOfxTzjBc4g8tZ/EJBoJBRqL01fysJBJoKua7YCSsHXJFhcYoJv5djGxtciJALu3rnf4Zt8exRLhCRUePu/+C25ag+aCzk9ymRFTiFbOnYO+IN2ox5iyZ/eLPPj8J6NmlzccvAUlCjMHsX+kVfIOoTdm5vBL4zZGd3tABli1SIi++gztIEKTUrlvJ709djQdVV1TwSQXUo+wZD8hhVxcYcBKZEkadhaiaI9FSz1EvUzMc+bMRUuY9gu4FNhnKhnwcFwPP7uW+lwKrg/3qOYL3h6VdFOBgEZlUu6BNa94QoeqVKD0IrgX69WFvhQv2OrvXXJ6/M2PCc0v416VDAN6ttWatXID2AYi2xWdr6RLYRo4n4dSe42xQjm2+6YOyttlrfsK1dpmMHwrCzKahKScHJ+UAzquY3AMjXzlfSDGJadUNH2DpANeNTJ8Q4W6tBvnki94QMUXK7yL08YEMolzucfbNKbdb0Htk256e93aWEjYI8zi2+OGpWJO4UQjWSwaK13WnELpp6BjGb38J5wY+l5fK3n8b5hfdou0lNDYoyyF+asEs6vSUnlMlsBsTa+eySxghTAclgr1/GY3/Wbg5Y2yM8aDJI11PIFOTxG0j0SajDZyCTN6Px65tWhZrPOxUUGmaDbvO39S6vxOg5gBLlEAQBYUaXozjmaXghHCiPFLmnZXJR25+Xj1MUlAaf2nhGE1dTWIBqrHsfXrq1LgyUyJPky8YpJZvkXfEz2E1ym4fjwQ0oqvttF9SPOQ0uINIfdtmZkBmWz0R2MwbhNpVvWKmpaRIKUJSNKXYJzY3b1o2FAzDzAkpVe5ZJRrtVrMJdvRNMjvtdCT7XrB/TzbqI4jBoIwWHBVgzHKIlYcqI9QcjETX4GvfBGC72iob5gWgOshIQYIVge6bCqeL4liU+HPp9Emr63eb0zMzlibRFOCKE9snt9EvZFACnJV8z55aUH3+aq/1I5tTweji/+w8sKWOvneJ0ruztV9cAnYBG1bJrJkB3ao/cxSKmMHREr7CxpVFMOrOsXAhOUF6h6sWq6bUvs9f/aaoTEjRqy85rAT1ggC25JthQ1ISkb7ZV0SnNJ7hCzKpiGf4ciMirIDp2LFek6/WOC7k4glM+Q1DzTLFKtN4RYFUSgz1zDVri8WCytkFhwnAs/goA8S0AsbRI2dqCTy7/n88mDnOtj0T3kdFYHAfa+T/utG/357/ijMnO7+WzCGdTXE6efkOGmws9utIW6yZt7A5DKDYp7L/aAzAJ8mjtq7gd2MeqlpkT7UFHRm94TIlkyVHOQadDTOiJKoqQk9PNjX6Lw8Yle6e6uFhGsd5lnKPxbvqkx4D6QjNfXVVoQ04JMDPIxnssCv4VmWaDKj4pFQ/8SfEIPWqFz+/KJbx8WZRVJkcTW6DvWaDG74pPxiLjanfjCvjx5DzKrtNQ33l04gkXd9BLlDa0r1jcaJ022P+llQAVlB4H0Q5YqS23/qQR4fLL7i10pqE2isOmzui8aCXILOqf9uRfjcJTtBA6+v7gKpnBqJJXPvbzMrgmtYkCfCQ+MKdDa/m7RQ8ZauZN4o6R1FIynzqrba6TeC2mi9WD+ocAqrjmdouOHCP5OMNRWsbWY3grCQG4Hkh5K5+nGUWxg4LnuN6mcObA1p+VhRXJJv4KCrFXZmaQJcxsmVUy+bTn35VhQO1+0g/gmlI3t6rbHWrHD4i0oJ95psboJhdaGyr3XEg2ZsmAxQbEkRPXjs1vNwVABJ3KKKBx1RhzIXh6cNJ1PIoeZJT2ZONIZ9qfnwvgjGPdyFW9oYJb58bP5ATpAHEZgUEeDcrl0cKgsbin1dgO6VdWzZJEorv0lsdTtFU/O3jz10YQcBKfUrb69ONabNYeDkwFUT7n3V73idmm2eh
---
kind: secret
name: gpg_key
data: fOcoV0g2lmxOlA5pvDhH8jjHElq32Ey+5Yo6qnZ/nLSY+1lvxhWmJG44npAhNxLeDRzl2nTYKwNEOx/zXAbQuLOlINw3RjOy4qsfQFqY5rBERkNuq1Bm0xf42b5WlgGRezEOjjW5AY3YfXRaQ7l93SlL9YwinOmVI3yIQIT/ZLKRxb3V24QNHOJuuBhMs7S2gftQoowmdpl373ucacGpMf9LZEsSDgGrR9476M3qleP+KU+CcFAX24PeFjyG0VoWFdpeyRcAnhccIzfnvKWAHuVNKStwuEzOMbAPQ0h/bCUH7JYuDQjP+IUA1wRsqTpRea3rB4wjj/p17JDI+pzPF3uVeVwAjj3TQrIN9eQY+Phn/NXjKB6OLV7+lKUBAhSmh4QePkOAV8mRKzmRkLvrmwwRjYvFvCbVcKWlOoUsqjlX1QkU+Ufn2IxepF17zl204hBfe2e7g8CVbttjpUT7KkL62tk1b85gc6B6l7HxGlY59+Zw4aOBoNkVVO90IC1aVMektTWPLGMudXdSX+vBVSmjT4uC7RWF1M0lyszyzI5HHSrv81t7jZjkRItV0wXACjvg9hsSUgsUeD4b/T5T4P/KXyxWFFuXII+OuhCkbZJTEzUS21OhvzXHp+qgTjMjNfg5i+oGz8OvszrO0IxHhezJTjjgjjYKn+9geHa0Y+LlwRinoygXunqcs4cYW5Af9TEhboD848WzoqA634emC10h+Tsd3vn/JZfgK3XXA0cUQqj+X4SIBJrvcb2EMcb2bRkW/0NCLzvEzKgH31Pwuxjsnnc75sOmSStuaXvAPCxSDzdlUpGdg+sAa9OcsKHUrvSnCN7pL/rL/WI2qjjc0rmU9gLQWsfdapiRtEdzWHA1lmkYnnxLNCcxC2RXfJGBBT7DrxBpoTj7UyGxjiEt3EVKsXn/t05PjugSC2hhloN5FA6WvMTK2pVQBgdB6q78YYVw3ZZTZ+POGXeYU7Dr0H7A8NMavF3cwWZ1RkMutngZWpfNNK/YkWPPmLJO+DKNZWsRNPiM+UD5jV55Btgv2TeyuY0CqOo5YJ64oGBSBOpqsfGwbK2PSRiDW5ToNk9FNePWjljwmOpnvkKIOq8crg70YbKnFGntg996m9kAWahdXkJ09idvRX/OyRawJxAqtDYQA0qarf3lmF/LdegOGTaSdfhRy+Y31M4rKnRrA/wOT9NQX873csW0nWDyUJCz1PkXOMYIi29MMDVr/t+GIm9/vrE1FDAW/Z6aYb1ttOlEF4pU0a4tvyO2ljfHqkpy9M7885uzJnv+oZyAZv1ZzRQHPItsXo8cHVfLScMkEYmw2MQXezsV0OLOuPC7mtlu2ozXrrIixI5OnRMHiehRyKGEMDDshBv/6XCuZeRnfbDfyfqZSw0xrkMBVyt9vA50F04HGXgHMEZOtNtTGhydAnyxnSQFrfkwKGexggrKKjoG7QJHzUkNKNuC8KPtLsHYWmna/JMAWo1fuE0/3ttA1C8VcxWiHztkHvaMuSdB9rJZMId752IEEUgMDNsF6kvODVTJDLAIyc9pn+aOaI3SGLPVjf6ugLK+j7kq5BAaPysPfDHZ4VpE/nuZeJaptkH1Brb9krOZ75dPnjrZi+RkwfQ8rxI2aQFZnQ5Kp2uqPUWZcpLWiQ+DYfv55UFrxtYvWHdAGr2wUQSjCg/iaHuKzVyV06UU2G7VRMgo/xaS9zAQ0do3u6NM004OwUNYuo98+aGnDZtJwDk7BaODlpBGtZzy4WSNlPDLpDar2an+OYBC7JEEoUbcsj5lFcWAY3VF7qClceph8QwBnxboH3G75f2BbUi2KhMiO1Cpe3KHSMua3SAlgSBST+94kqsJbavFI2+o47NhxK51plygdSorMbykDhJQg7za1BO3uK5TFhAfe/miJR4AIynfQTg9Ml2qDU8rQy8F3/IeWhf6FAN0Td349lSBqOA+TEzcSsqnjdQ2W9Vvn6fHjRVBo9PVaEwo+Oyy9N666Qm187OMYSUGI1dSX1+3eHrAHwqssfYbo/WUHzq/OE0PoLRFiaup2vK13mosQxZwatOj0g2ojygFnyegL9CUflvcWc06pg9aAurGtFTW3Q6+67IyrGWzOyjhUJ1t+FyiW2JeN8eqyM8UXWm2LAFGaI/ExMpzx4agB2huvlIEJPniU+kIYp1yChC8I4BaSZGlO9PKpWWw9HltHPPeTJd/qYwIv95ZuGzs+dChYQAyoE91aLnpHYdz6OwlSjLQXFBNBrJQQhbLsLu1T6EbpkmfB5+fWdirG0BnwpIixWDT1NPStkZ2V6ob2PPDZdjShqkzwcbixrwNSk0lZm+NQHE1hmxtWh6ggC4uoeKcGO+qnNWWE1/t5gJzjyUQdzoDGwMBzMuOmGyqj5fwXW7wQyk6r+gWWZ4M2ONwu5ondv+TAF/1o9dZ5lDlDH/Wfy9w8Ne2P+o/eGhkfZQFUmGX4VZxANXUmAbaV3cV6lP8ZRjYLH9t2dbaXxZi4YGyGD5Jb2EO3zjDiCZlboNRrPUE/pakhM2xXrI3L0ZFOcFIDbgyOkmObWmpZhXvqXxgp46EkZwYfhhUNTDdp1Ta4WI7eiHv2uKY5VRk49aGAHlSSxTOSxqjP5DkkujfrfIs0pXi9IFlJhVahxOQ2XtkOcL1vGIRGvl6+CQOx+/aSZJl7CyTlLWfv4++XDsmLFifSIKZ9Wbyg9j9OGlyCgowuVQyhOyY8lbTMUbhaCavHuibtfIOdk4g2FL4//FSilhx8aYVPqef+uzLw2Rnf0B9f+tlwn4aYYmX4BpKEegzeDsJ+yxMf8iSxPdErUD9CwAOmzosdKo96YDRuOeV3mJL0Y/eXXkyyTC1mjh9bT0MKZ9Wr5Qdipa4Ujw46lPTgxtyG4mcfDpQhKtErI1ZTFFFnctLqgdAd+nXW1fNvXCS5a+KJAnG0rEhd1DomBtV77x8hWOLyJxxDgewbSyxeDegP8UIBJ9Lix9+xSr/SA9LGFjdg4xAX4ZxIJR7VjvkXEdEXeQpLlOg+sY9gpTpDerf2sk6egpHiTzMDIqKTsByhQt8rpewU2xRhML+2O203Y08brB/BV96OAybq51chzJbeBSSNUcyoZV3aXgM2dkOJptgyxA0fO1WUaoNJw3sMZwFEmMhsbMu0Ch0/xMXPm2qK9W0exm1+QG3beiIbtjkdctWadIAkaVkVxb72OvhtR4Sj0lMC6ssrKOx/knUz6R7BfQhqcjR07yrBg6arUbImUcuZp6bpLrIOCFwI6M64LUQGI/0AzMtaZtdx/3+cAYRQtFsMnWMEJT/hZWJXnlkKvIooIlMZCCHP77jeUcPuEZ2p59ypHEA5zG4OMIUSQY627PcV9rZauHNDE7z01uAfBgpUr+dcw0UREWukOdJYfgfO6UJUR8E4GQAp7tVeErwY/YoC3EqFvJ9UynF4ytW55V4IunSRpIFXLtjjbpSRnsXGEg1eU60fKwlV+3hou4u2Z0vTC55RXXYo23gI03LE1f7gccbhcHvJu85Ef7InOMpwMD8koM1ROhS92VatcVVqyOPGkbOKXvxBgcSmIkdtTrmA/y8C3YsOUilt5kYjBtcfbktKSRHrISUhmSJwgYV4rjxTGbiH8sSkMoip0z/QtXd9VCsW0bqCEyO18A5f3bQ19mXbVwoYyyFtuIQipLKZluKb7xxA2KOYW4q28AUlMtn9HzV8CgdNFP9zKTkvPIIQcT3T72p8EPZxLslZcVt07g8Ql7916Ng62P6Y4EebXLWT5og51qml7q/6qJQ+vuR20S/igdYRK2LxOaNSprdKyxSRf0HGcXIvwsTgQlRbwAFT43CXxi7wfycWATCaKZ3+ZYU1kDGCm9bJXCpGaXq9ZOrwdd4JtzeZkSQ4OxH2SjSBILV/lEN7TGGGCz1q+YKF4jVwAqRZwS39Nq+EHGGyHPWZw4z6EoJvm4OFgc3gkhmFAHreAqnOHexfoYiz3rwx6Ms0Xc5bQs6IQSqdrnjmmvGPaBrF7JIkN0mzfInFSdbl6GMmIoGt/OqPc6ZujDxkY4+FOfHX8yJC5uqiNkd8jB+TkL51opQu7HPufad6cMUUBLXNG6K1qdfKurCbaV4VBZlAFc0A2QbdYQrxXjjY8I1e4IrIK1qoJAw/SB3qPks/3cdkFwHUstRMLqLeQvMedlp02DpS94V+I4rrxPNNJ/ZDSAFo5G01bAIIMNkZZu4g19A7p/OWztaCFFWiUEZvN8Jx8rlmQtANa3Z5DeuKvD3OWbV7iNnLzN6zxtL2jzcHvnsacDOAHlEYZoAf1zLKgvSSIA0iU6nwZsYJ1sXwt2H8HxUw/ZJRx2cc8Y9i+6+4zw7tSoqzENvDqDxxJYqRe227M3NiYh1pV7rdQvIY0NGd5/h75MRhmOuU6n87DwM9Y32IweLNOxML1U+PqZwGAC8muJkiPnigyRpoG4LOfZr2q8ZLA5jkza0YlCbQ+CBDfHPE/ekm9PQQzkocC3cA/xvmCqM5hS/svHePQiSeLIi7gNvlzD/8wGsC9lTrWh/L6jGgDHAv17Am3jX6uaqAEo6k75GS3wPXRzFH3S8XYUl/8OFrUA+/HyntJxp1nB7mIXpqOJG9D+sJA4m4Jbo/JwOclfVd1Bl7aCXmCrZEM5x23ORaVYB9SwrYh4Yz97u+/NRIC59/nFBeX76r6xIo0fstx15UUzlhowp0Sycz/S/qkCncZtb/5QnrYN2r/7T53ISoAt8crr7Pd4q3W0nE10wQaqGQyQRYzF0a0VnMeYWfBQLR5l4l9U655rc1yvhaiieoOEjNVwRsNn5sYkTKxr7r2bvvg4WU8WnscKVnK5+XiPfSpztO7uy2Z9d67dV+a9/1+bEZNR9yiil2OJ+UrRfNJDAHE3STUJ+Zvn6cFGSAQcUMqtzMFIDuCfGYHHBW5pDLyVPILsg0T9oIoaaemmcv0Lky7hDvFg6XGOYy9SLtFKe7S/hT69xpYK27xk3v9lxikqQln3RJlaDZ9/hJ0IrfsM/ak20HTVklD6EPryTaAxcktlbXrnGLJtvgAZkYLus3jvg36ylus1QPxd9HlahQ0085c8pIdSGuLyb8orVEk0hBPRbDF+BRL8JbM3CaihqO61PpQ+1nNZf95sFknU6FgRcCunfBVPyzC9nD/nBgMtQTv8AskOmbJkKlvRwIjowlsLkII+duejH79Ux7EWKUU7sDV1IgfJOV//qe1uJZZH7VzWtZx3PNxI1WMYsJ/PtdSI1XvG9Tv2wlGZOuum9mTSJgIHiGT6hurSdFEo57ATbhzEOYtn1JArfc1bMT7K2a2TBAA3V6rloG5E9Wxu6g2E/o4Bjo75Qru8caC9lc0DPR576rW0QH2vukgZh1q4MW+u9IxReuA1QWK2bxK1++t6MA64tP+qtdyceqVK3d3qGjjCNtKQEih2TN36WKeRdstJZv9nOF3OfUwd2+ZL3dPuLuRlGSptkLXWahCHEYxzHTZEhBpf8rf5uSZMuKSQ7U3tG0xpCEwrzTHeGqgCUcvbkdK8HPGbHzP/UzIgi8AoUxtaZ3kdT1ZYYa2OIR6HJjgENeUhS2WPajsMBPfzzVs8J+KKYpi2Eown7ILkiHIh5iLUJ9XKW1WKrSeDhS1t7i0IGglp9ZLIuKI6nLi96I22v4WqZ01ExFL81s48uJOQAB7na214U/yiNetD971dCmO9JZIkYrvQqXy+ONasl9zHoh3aQJpJ8GYH1PJym0RyKGHsmcesUz4zVUr6tihFxHpv20yekzcSho0m6BGOzhV/pteTl5MIT7HlBmJvrQENNc0mGQJjELG1bFNk9LFAa8RHNcJbuz80bcA/lvCoSgjRlFxMM3eoaBbpskqMc1MdmEZ5Z2naUMyAU4hrk4A0rG/XdltfPKdgacMB5p9JTyP3ep4Bva+okSQ43rUvxQobX+p9wikikxG/x/ZrVrVaSJkSC3gCyzVkWqNTnVXtGulpYOy61pmu7P11m7umJptj623/I4s7DmXLacJAYuax5WSVPXeqYpNsqdYGNz4bR6/sozzXbEOYV8UGPiqV/VzbFoTg2qUDnTws2bwkPBFvKPagfAY8usQMETdUzJ5MsxolNs2BStI7uorO/cfg6H30fG3M8waP2XWMgxBP2WjjrzOxta9i7cN/Xexvc9MzXpulvF3AK1zPefoeEROf6LyugLHMp23BlkbedMBJUxusf6/2sfGe8hnc+YCj34hGx3tpqetdoxuShusrafyLjDuLLDWNPH6YokJWYLO2Lml5aCP8Bvq5ra7lbjlwJAOrRUda+nbC6tNdOmVHP5xu3XZvThdHTF/3pHmvnqoXw51PNb9Gslf0VpivPONx8ee3oYeZ7uPbrUOFBKmJ4JS+Nmqn9eNG6jU0E+hQIZ2x5fkNzYbhZMwBn+lkOhaNd/9cSWuIPLWEDf8R/aeSU7uU7sYHrZXWn2QRnHNkxjUR1Kjn5HeagOcV/Cujmkqe+z8Z+oXiZ4G3WqAEMmTvG+bFgM37R/bYAJj79Mgt7AhlCeVLSBiaTPRUgsjaL/YB+hnmuHyLowRUvfZv6EnoyD+MHTa9veaEhjUHAyhFkCZ8pBK/LaGYqsfD6oV3fsHaU54tXBKgyO6fGYOkNE97rMIDcToSIxDgzf94Ywr+mxQIB8BXnSSDdQD0X7CD3ifSHVMOjaKCZRwtJlNi5K9+ssq7w3pOUjbP1KcVQQJlJjteuy0bOkElKTw==
---
kind: signature
hmac: 92fed9a83023951b3a7452cbe0fbb46a8c1e96ff0bb580efceffa1b268f22919

...
=======
- name: build
  image: node:12
  commands:
  - npm install
  - npm test
  - npm run build
- name: npm
  image: plugins/npm
  settings:
    registry: 'https://registry.npmjs.org/'
    token:
      from_secret: npm_token
  when:
    event: tag
---
kind: secret
name: npm_token
data: 2OpPyM5AvvWBBJDkFSNb8DFclq8lgtt4nQhdTXlAI7wSGForJgMDZbr7VtTCDVoUFx7wRHYIPj3hAcs5TifDFg==
>>>>>>> origin/dev
